dash_panel/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from dash_panel import views as views_dash_panel
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'dash_panel'

urlpatterns = [
    url(r'^$', views_dash_panel.dash_panel_login_view, name="dash_panel_login"),
    url(r'^index/$', views_dash_panel.dash_panel_index_view_, name="dash_panel_index_"),
    url(r'^login/$', views_dash_panel.dash_panel_index_view, name="dash_panel_login"),
    # url(r'^check_login/$', views_dash_panel.check_login, name="dash_panel_check_login"),
    url(r'^add_user/$', views_dash_panel.add_user, name="add_user"),
    url(r'^add_portfolio_item/$', views_dash_panel.add_portfolio_item, name="add_portfolio_item"),
    url(r'^portfolio_item_details/(?P<project_id>\d+)/$', views_dash_panel.portfolio_item_details, name="portfolio_item_details"),
    url(r'^portfolio_list/$', views_dash_panel.portfolio_list, name="portfolio_list"),
    url(r'^del_fotos_from_galley/$', views_dash_panel.del_foto_from_gallery, name="del_foto_from_gallery"),
    url(r'^del_portfolio_item/$', views_dash_panel.del_portfolio_item, name="del_portfolio_item"),
]

# if settings.DEBUG:
# urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dfacade/urls.py
from django.contrib import admin
from django.conf.urls import url, include
# from django.urls import path
from main import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^$', views.index_view, name="index"),
    url(r'portfolio_details/(?P<project_id>\d+)/$', views.portfolio_details_view, name="portfolio_details"),
    url(r'contacts/', views.contacts, name="contacts"),
    url(r'compet/', views.goto_compet, name="goto_compet"),
    url(r'projects/', views.goto_project, name="goto_projects"),
    url(r'why_us/', views.goto_why_us, name="goto_why_us"),
    url(r'directions/', views.goto_directions, name="goto_directions"),
    url(r'dash_panel/', include('dash_panel.urls')),
    url(r'site_message/', views.message_from_site, name="site_message")
    # url(r'^cart_for_checkout/(?P<cart_id>\d+)/$', main_view.cart_for_checkout, name='cart_for_checkout'),

]

# if settings.DEBUG:
urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dash_panel/models.py
from django.db import models

# Create your models here.

dash_panel/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.decorators import login_required
from main.models import User, Role, UserProfile, PortfolioItem, PortfolioItemImages, PortfolioItemImagesBig, PortfolioItemImagesSmall
from django.contrib.auth import authenticate, login, logout


# Create your views here.


def dash_panel_login_view(request):
    logout(request)
    context = {
    }
    return render(request, 'login.html', context)


# @login_required(redirect_field_name=None, login_url='/dash_panel')
def dash_panel_index_view(request):
    if request.method == 'POST':
        login_ = request.POST['login']
        password = request.POST['password']
        # user = User()
        # user.password = password
        # user.email = email
        # user.save()
        print(login_ + ' ' + password)
        user = authenticate(username=login_, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                print('logged')

            return HttpResponse(user.id)
        else:
            return HttpResponse('error')

    context = {}
    print("dfsdfsdfsdf")
    return render(request, 'base_dash_panel.html')


@login_required(redirect_field_name=None, login_url='/dash_panel')
def dash_panel_index_view_(request):
    return render(request, 'base_dash_panel.html')


def check_login(request):

    context = {}
    print("dfsdfsdfsdf")
    return render(request, 'base_dash_panel.html', context)


@login_required(redirect_field_name=None, login_url='/dash_panel')
def add_user(request):
    context = {
        'roles': Role.objects.all()

    }

    return render(request, 'add_user.html', context)


@login_required(redirect_field_name=None, login_url='/dash_panel')
def portfolio_list(request):
    context = {
        'portfolio_list': PortfolioItem.objects.all()

    }

    return render(request, 'portfolio_list.html', context)


@login_required(redirect_field_name=None, login_url='/dash_panel')
def add_portfolio_item(request):

    if request.method == 'POST':
        data = request.POST
        name_ = data.get('name')
        short_name = data.get('short_name')
        client = data.get('client')
        period = data.get('period')
        sum_ = data.get('sum')
        vol = data.get('vol')
        project_id = data.get('project_id')
        if project_id:
            item = PortfolioItem.objects.get(id=project_id)
        else:
            item = PortfolioItem()
        item.client = client
        item.name = name_
        item.short_name = short_name
        item.period = period
        item.sum = sum_
        item.vol = vol
        item.save()
        image_num = 1

        for file_key in request.FILES.keys():
            print('fk' + str(file_key))
            for file in request.FILES.getlist(file_key):
                print('file_name = ' + str(file.name.encode('utf-8')))
                if '370' in file.name:
                    # item_img = PortfolioItemImages()
                    # item_img.image = file
                    # item_img.item = item
                    # item_img.save()
                    item.main_image = file
                    item.save()
                else:
                    item_img = PortfolioItemImagesBig()
                    item_img.item = item
                    item_img.name = file
                    item_img.image = file
                    # if first_time:
                    #     item.main_image = file
                    #     item.save()
                    #     first_time = False
                    item_img.save()
                image_num += 1
        return HttpResponse()



    # if request.method == 'POST':
    #     name_ = request.POST['name']
    #     client = request.POST['client']
    #     period = request.POST['period']
    #     sum_ = request.POST['sum']
    #     vol = request.POST['vol']
    #     item = PortfolioItem()
    #     item.client = client
    #     item.name = name_
    #     item.period = period
    #     item.sum = sum_
    #     item.vol = vol
    #     item.save()
    #     return HttpResponse('ok')
    context = {
        # 'roles': Role.objects.all()

    }

    return render(request, 'add_portfolio_item.html', context)


def portfolio_item_details(request, project_id):
    portfolio_item = PortfolioItem.objects.get(id=project_id)
    images_big = PortfolioItemImagesBig.objects.filter(item=portfolio_item)
    # images_small = PortfolioItemImagesSmall.objects.filter(item=portfolio_item)
    context = {
        'portfolio_item': portfolio_item,
        'images_big': images_big,
        # 'images_small': images_small,
    }
    return render(request, 'portfolio_item_details.html', context)


def del_foto_from_gallery(request):
    if request.method == 'POST':
        data = request.POST
        project_id = data.get('project_id')
        item = PortfolioItem.objects.get(id=project_id)
        PortfolioItemImages.objects.filter(item=item).delete()
        PortfolioItemImagesBig.objects.filter(item=item).delete()
        item.main_image = ''
        item.save()
        return HttpResponse('ok')


def del_portfolio_item(request):
    if request.method == 'POST':
        data = request.POST
        project_id = data.get('project_id')
        item = PortfolioItem.objects.get(id=project_id)
        PortfolioItemImagesBig.objects.filter(item=item).delete()
        item.delete()
        return HttpResponse('ok')

dash_panel/templates/add_user.html
{% extends 'base_dash_panel.html' %}

{% load staticfiles %}



{% block links %}

{#    <link href="{% static 'admin_panel/bower_components/bootstrap/dist/css/' %}" rel="stylesheet" type="text/css"/>#}
    <link href="{% static 'admin_panel/bower_components/switchery/dist/switchery.min.css' %}" rel="stylesheet" type="text/css"/>


{% endblock %}

{% block content %}
            <div class="page-wrapper" style="min-height: 337px;">
				<div class="container-fluid">

					<!-- Title -->
					<div class="row heading-bg">
						<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
						  <h5 class="txt-dark">Добавление пользователя</h5>
						</div>
						<!-- Breadcrumb -->
{#						<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">#}
{#						  <ol class="breadcrumb">#}
{#							<li><a href="index.html">Dashboard</a></li>#}
{#							<li><a href="#"><span>form</span></a></li>#}
{#							<li class="active"><span>form-element</span></li>#}
{#						  </ol>#}
{#						</div>#}
						<!-- /Breadcrumb -->
					</div>
					<!-- /Title -->

					<!-- Row -->
					<div class="row">
						<div class="col-sm-12">
							<div class="panel panel-default card-view">
								<div class="panel-heading">
									<div class="pull-left">
										<h6 class="panel-title txt-dark">Форма пользователя</h6>
									</div>
									<div class="clearfix"></div>
								</div>
								<div class="panel-wrapper collapse in">
									<div class="panel-body">
										<div class="form-wrap">
											<form id="user_form" method="POST">{% csrf_token %}

                                                <div class="form-group">
                                                    <label class="control-label mb-10">Select box</label>
                                                        <div class="btn-group bootstrap-select dropup"><button type="button" class="btn dropdown-toggle form-control btn-default btn-outline" data-toggle="dropdown" role="button" title="Mustard" aria-expanded="false"><span class="filter-option pull-left">Mustard</span>&nbsp;<span class="bs-caret"><span class="caret"></span></span></button><div class="dropdown-menu open" role="combobox" style="max-height: 138px; overflow: hidden; min-height: 0px;"><ul class="dropdown-menu inner" role="listbox" aria-expanded="false" style="max-height: 128px; overflow-y: auto; min-height: 0px;"><li data-original-index="0" class="selected ms-hover"><a tabindex="0" class="" style="" data-tokens="null" role="option" aria-disabled="false" aria-selected="true"><span class="text">Mustard</span><span class="glyphicon glyphicon-ok check-mark"></span></a></li><li data-original-index="1"><a tabindex="0" class="" style="" data-tokens="null" role="option" aria-disabled="false" aria-selected="false"><span class="text">Ketchup</span><span class="glyphicon glyphicon-ok check-mark"></span></a></li><li data-original-index="2"><a tabindex="0" class="" style="" data-tokens="null" role="option" aria-disabled="false" aria-selected="false"><span class="text">Relish</span><span class="glyphicon glyphicon-ok check-mark"></span></a></li></ul></div><select class="selectpicker" data-style="form-control btn-default btn-outline" tabindex="-98">
                                                            <option>Mustard</option>
                                                            <option>Ketchup</option>
                                                            <option>Relish</option>
                                                        </select></div>
                                                </div>




												<div class="form-group">
													<label class="control-label mb-10 text-left">ФИО</label>
													<input class="form-control" id="fio_input" name="fio_input">
												</div>
												<div class="form-group">
													<label class="control-label mb-10 text-left" for="email_input">Email</label>
													<input type="email" id="email_input" name="email_input" class="form-control">
												</div>
												<div class="form-group">
													<label class="control-label mb-10 text-left" for="tel_input">Телефон</label>
													<input id="tel_input" name="tel_input" class="form-control">
												</div>
												<div class="form-group">
													<label class="control-label mb-10 text-left" for="login_input">Логин</label>
													<input id="login_input" name="login_input" class="form-control">
												</div>
												<div class="form-group">
													<label class="control-label mb-10 text-left" for="pass_input">Пароль</label>
													<input id="pass_input" name="pass_input" class="form-control">
												</div>
												<div class="form-group">
													<label class="control-label mb-10 text-left">Примечания</label>
													<textarea class="form-control" rows="5"></textarea>
												</div>
											</form>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- /Row -->

				</div>

				<!-- Footer -->
{#				<footer class="footer container-fluid pl-30 pr-30">#}
{#					<div class="row">#}
{#						<div class="col-sm-12">#}
{#							<p>2018 © Winkle. Pampered by Hencework</p>#}
{#						</div>#}
{#					</div>#}
{#				</footer>#}
				<!-- /Footer -->

			</div>
        <button id="save_btn" class="btn  btn-primary btn-rounded btn-corner-fixed"><i class="ti-save font-size-20-imp"></i></button>

{% endblock %}
{% block script %}

    <script src="{% static 'admin_panel/bower_components/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'admin_panel/bower_components/select2/dist/js/select2.full.min.js' %}"></script>
    <script src="{% static 'admin_panel/bower_components/switchery/dist/switchery.min.js' %}"></script>
    <script src="{% static 'admin_panel/js/form-advance-data.js' %}"></script>


    <script>
            $('#save_btn').on('click', function (e) {
                e.preventDefault();
                console.log('submit');
                if ($('#login_input').val() == '' || $('#pass_input').val() == ''){
                    swal({
                        title: 'Ошибка',
                        text: 'Email и пароль должны быть указаны',
                        type: 'error',
                        confirmButtonText: 'Ok',
                        closeOnConfirm: false
                    });
                }else {
                    var formdata = new FormData($('#login_form').get(0));
                    $.ajax({
                        url: "{% url 'dash_panel:check_login' %}",
                        type: 'POST',

                        data: formdata,


                        processData: false,
                        contentType: false,
                        error: function(data){
                            console.log('error' + data);
                        },
                        success:function (data) {
            {#                console.log(''data);#}
                            if (data == 'error'){
                                swal({
                                    title: 'Ошибка',
                                    text: 'Email или пароль указаны не верно',
                                    type: 'error',
                                    confirmButtonText: 'Ok',
                                    closeOnConfirm: false
                                });

                            }else {

                                swal({
                                    title: 'Информация сохранена',
                                    text: 'Информация о пользователе успешно сохранена',
                                    type: 'success',
                                    confirmButtonColor: '#3085d6',
                                    confirmButtonText: 'Ок',
                                    closeOnConfirm: true,
                                });

                                window.location.href = '/dash_panel/index';
{#                                window.location.href = '/dash_panel/' + data;#}
                            }
                        }
                    });

                }

            })

    </script>

{% endblock %}

dash_panel/templates/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
		<title>Winkle I Fast build Admin dashboard for any platform</title>
		<meta name="description" content="Winkle is a Dashboard & Admin Site Responsive Template by hencework." />
		<meta name="keywords" content="admin, admin dashboard, admin template, cms, crm, Winkle Admin, Winkleadmin, premium admin templates, responsive admin, sass, panel, software, ui, visualization, web app, application" />
		<meta name="author" content="hencework"/>
		
		<!-- Favicon -->
		<link rel="shortcut icon" href="favicon.ico">
		<link rel="icon" href="favicon.ico" type="image/x-icon">
		
		<!-- vector map CSS -->
		<link href="{% static 'admin_panel/bower_components/jasny-bootstrap/dist/css/jasny-bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
		<link href="{% static 'admin_panel/bower_components/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
		<link href="{% static 'admin_panel/bower_components/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css' %}" rel="stylesheet" type="text/css"/>
		<link href="{% static 'admin_panel/bower_components/sweetalert/dist/sweetalert.css' %}" rel="stylesheet" type="text/css"/>

		
		
		<!-- Custom CSS -->
		<link href="{% static 'admin_panel/css/style.css' %}" rel="stylesheet" type="text/css">
	</head>
	<body>
		<!--Preloader-->
		<div class="preloader-it">
			<div class="la-anim-1"></div>
		</div>
		<!--/Preloader-->
		
		<div class="wrapper  pa-0">
			<header class="sp-header">
				<div class="sp-logo-wrap pull-left">
					<a href="base_dash_panel.html">
						<img class="brand-img mr-10" src="{% static 'img/logo_white_200.png' %}" alt="brand"/>
					</a>
				</div>
{#				<div class="form-group mb-0 pull-right">#}
{#					<span class="inline-block pr-10 txt-light-grey">Don't have an account?</span>#}
{#					<a class="inline-block btn btn-warning  btn-rounded " href="signup.html">Sign Up</a>#}
{#				</div>#}
				<div class="clearfix"></div>
			</header>
			
			<!-- Main Content -->
			<div class="page-wrapper pa-0 ma-0 auth-page">
				<div class="container-fluid">
					<!-- Row -->
					<div class="table-struct full-width full-height">
						<div class="table-cell vertical-align-middle auth-form-wrap">
							<div class="auth-form  ml-auto mr-auto no-float card-view pt-30 pb-30">
								<div class="row">
									<div class="col-sm-12 col-xs-12">
										<div class="mb-30">
											<h3 class="text-center txt-dark mb-10">Вход в систему</h3>
{#											<h6 class="text-center nonecase-font txt-grey">Enter your details below</h6>#}
										</div>	
										<div class="form-wrap">
											<form id="login_form" method="POST">{% csrf_token %}
												<div class="form-group">
													<label class="control-label mb-10" for="login">Логин</label>
													<input class="form-control" required="" id="login" name="login" placeholder="Введите логин">
												</div>
												<div class="form-group">
													<label class="pull-left control-label mb-10" for="password">Пароль</label>
{#													<a class="capitalize-font txt-orange block mb-10 pull-right font-12" href="forgot-password.html">forgot password ?</a>#}
													<div class="clearfix"></div>
													<input type="" class="form-control" required="" id="password" name="password" placeholder="Введите пароль">
												</div>
												
												<div class="form-group">
													<div class="checkbox checkbox-primary pr-10 pull-left">
														<input id="checkbox_2" required="" type="checkbox">
														<label for="checkbox_2"> Оставаться в системе</label>
													</div>
													<div class="clearfix"></div>
												</div>
												<div class="form-group text-center">
													<button id="submit" type="submit" class="btn btn-warning  btn-rounded">войти</button>
												</div>
											</form>
										</div>
									</div>	
								</div>
							</div>
						</div>
					</div>
					<!-- /Row -->	
				</div>
				
			</div>
			<!-- /Main Content -->
		
		</div>
		<!-- /#wrapper -->
		
		<!-- JavaScript -->
		
		<!-- jQuery -->
		<script src="{% static 'admin_panel/bower_components/jquery/dist/jquery.min.js' %}"></script>
		
		<!-- Bootstrap Core JavaScript -->
		<script src="{% static 'admin_panel/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
		<script src="{% static 'admin_panel/bower_components/jasny-bootstrap/dist/js/jasny-bootstrap.min.js' %}"></script>

		<script src="{% static 'admin_panel/bower_components/sweetalert/dist/sweetalert.min.js' %}"></script>

		<!-- Slimscroll JavaScript -->
		<script src="{% static 'admin_panel/js/jquery.slimscroll.js' %}"></script>
		
		<!-- Init JavaScript -->
		<script src="{% static 'admin_panel/js/init.js' %}"></script>
		<script src="{% static 'admin_panel/js/jquery.cookie.js' %}"></script>

        <script>
            $('#submit').on('click', function (e) {
                e.preventDefault();
                console.log('submit');
                if ($('#login').val() == '' || $('#password').val() == ''){
                    swal({
                        title: 'Ошибка',
                        text: 'Email и пароль должны быть указаны',
                        type: 'error',
                        confirmButtonText: 'Ok',
                        closeOnConfirm: false
                    });
                }else {
                    var formdata = new FormData($('#login_form').get(0));
                    $.ajax({
                        url: "{% url 'dash_panel:dash_panel_login' %}",
                        type: 'POST',

                        data: formdata,


                        processData: false,
                        contentType: false,
                        error: function(data){
                            console.log('error' + data);
                        },
                        success:function (data) {
                            console.log("data - " + data);
                            if (data == 'error'){
                                swal({
                                    title: 'Ошибка',
                                    text: 'Email или пароль указаны не верно',
                                    type: 'error',
                                    confirmButtonText: 'Ok',
                                    closeOnConfirm: false
                                });

                            }else {
                                console.log($('#checkbox_2').prop('checked'));
                                if ($('#checkbox_2').prop('checked') == true){
                                    $.cookie('login', $('#login').val(), {path: '/'});
                                    $.cookie('password', $('#password').val(), {path: '/'});

                                }

                                swal({
                                    title: 'Пользователь найден',
                                    text: 'Удвление прошло успешно.',
                                    type: 'success',
                                    confirmButtonColor: '#3085d6',
                                    confirmButtonText: 'Ок',
                                    closeOnConfirm: true,
                                });

                                window.location.href = '/dash_panel/index';
{#                                window.location.href = '/dash_panel/' + data;#}
                            }
                        }
                    });

                }

            })

        </script>
	</body>
</html>

dash_panel/templates/portfolio_list.html
{% extends 'base_dash_panel.html' %}

{% load staticfiles %}



{% block links %}

{#    <link href="{% static 'admin_panel/bower_components/bootstrap/dist/css/' %}" rel="stylesheet" type="text/css"/>#}
    <link href="{% static 'admin_panel/bower_components/switchery/dist/switchery.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'admin_panel/bower_components/datatables/media/css/jquery.dataTables.min.css' %}" rel="stylesheet" type="text/css"/>


{% endblock %}

{% block content %}
		<div class="page-wrapper">
			<div class="container-fluid">

				<!-- Title -->
				<div class="row heading-bg">
					<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
					  <h5 class="txt-dark">Портфолио</h5>
					</div>
					<!-- Breadcrumb -->
					<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
					  <ol class="breadcrumb">
						<li><a href="index.html">Dashboard</a></li>
						<li><a href="#"><span>table</span></a></li>
						<li class="active"><span>data-table</span></li>
					  </ol>
					</div>
					<!-- /Breadcrumb -->
				</div>
				<!-- /Title -->

				<!-- Row -->
				<div class="row">
					<div class="col-sm-12">
						<div class="panel panel-default card-view">
							<div class="panel-heading">
								<div class="pull-left">
									<h6 class="panel-title txt-dark">Список проектов</h6>
								</div>
								<div class="clearfix"></div>
							</div>
							<div class="panel-wrapper collapse in">
								<div class="panel-body">
									<div class="table-wrap">
										<div class="table-responsive">
											<table id="datable_1" class="table table-hover display  pb-30" >
												<thead>
													<tr>
														<th>Заказчик</th>
														<th>Период</th>
														<th>Объект</th>
														<th>Сумма</th>
														<th>Объем</th>
														<th></th>
														<th></th>
													</tr>
												</thead>
												<tfoot>
													<tr>
														<th>Заказчик</th>
														<th>Период</th>
														<th>Объект</th>
														<th>Сумма</th>
														<th>Объем</th>
														<th></th>
														<th></th>
													</tr>
												</tfoot>
												<tbody>
                                                {% for item in portfolio_list %}
													<tr class="item cursor-pointer">
														<td>{{ item.client}}</td>
														<td>{{ item.period }}</td>
														<td>{{ item.name }}</td>
														<td>{{ item.sum }}</td>
														<td>{{ item.vol }}</td>
														<td><i class="ti-close cursor-pointer" id="{{ item.id }}"></i></td>
														<td><i class="ti-pencil cursor-pointer" id="{{ item.id }}"></i></td>
													</tr>
                                                {% endfor %}
												</tbody>
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- /Row -->

			</div>

			<!-- Footer -->
			<footer class="footer container-fluid pl-30 pr-30">
				<div class="row">
					<div class="col-sm-12">
						<p>2018 &copy; Winkle. Pampered by Hencework</p>
					</div>
				</div>
			</footer>
			<!-- /Footer -->

		</div>
		<!-- /Main Content -->

{% endblock %}
{% block script %}

    <script src="{% static 'admin_panel/bower_components/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'admin_panel/bower_components/select2/dist/js/select2.full.min.js' %}"></script>
    <script src="{% static 'admin_panel/bower_components/switchery/dist/switchery.min.js' %}"></script>
    <script src="{% static 'admin_panel/bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
{#    <script src="{% static 'admin_panel/js/form-advance-data.js' %}"></script>#}


    <script>

        $('.ti-close').on('click', function (e) {
            console.log('ti closw');
            var id = $(this).prop('id');
            e.preventDefault();
            var data = new FormData();
            data.append('project_id', id);
            data.append('csrfmiddlewaretoken', '{{ csrf_token }}');

                $.ajax({
                    url: '{% url 'dash_panel:del_portfolio_item' %}',
                    type: 'POST',
                    data: data,
                    processData: false,
                    contentType: false,
                    error: function(data){
                        swal({
                            title: 'Ошибка сервера',
                            text: 'Возникла ошибка при сохранении. Попробуйте позже.',
                            type: 'warning'
                        });
                    },
                    success:function (data) {
                        swal({
                            title: 'Информация обнавлена',
                            text: 'Проект удален',
                            type: 'success',
                            confirmButtonColor: '#3085d6',
                            confirmButtonText: 'Ок',
                            closeOnConfirm: true,
                        },
                        function (isConfirm) {
                            if (isConfirm){

                                window.location.href = '/dash_panel/portfolio_list/';
                            }

                        });

                    }
                });

        });

        $('.ti-pencil').on('click', function () {
            window.location.href = '/dash_panel/portfolio_item_details/' + $(this).prop('id');
        });

    </script>

{% endblock %}